# Site
name: 'Calories Queen'
description: 'Everything about your Nutrition'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: ''
email: 'caloriesqueen@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Calories Queen
      site:           https://www.instagram.com/caloriesqueen
      avatar:         /assets/images/demo1.jpg
      bio:            "Hi, I am Yashica, the owner of Calories Queen. I am NESTA Certified Nutrition Coach and a graduate from IIT Delhi. I hope you like this blog!"
      email:          caloriesqueen@gmail.com
      twitter:        https://twitter.com/caloriesqueen1

    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]